# Generated by Django 4.1.6 on 2023-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
