# Generated by Django 4.1.5 on 2023-02-21 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_sample_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
