# Generated by Django 4.1.5 on 2023-03-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_rack_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='date',
        ),
    ]
