# Generated by Django 4.1.5 on 2023-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_remove_rack_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
