# Generated by Django 4.1.5 on 2023-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_rack_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wedesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='rack',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
